providers = ["python"]

[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["pip3 install -r requirements.txt"]

[start]
cmd = "python3 manage.py migrate --no-input && python3 manage.py collectstatic --no-input && gunicorn config.wsgi:application --workers 2 --threads 2 --bind 0.0.0.0:$PORT"
