[build]
builder = "nixpacks"

[deploy]
startCommand = "python3 manage.py migrate --no-input && python3 manage.py collectstatic --no-input && python3 seed_db.py && gunicorn config.wsgi:application --workers 2 --threads 2 --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

