# Generated by Django 6.0.3 on 2026-03-09 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('tagline', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('security_level', models.CharField(choices=[('CRITICAL', 'CRITICAL'), ('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], max_length=20)),
                ('domain', models.CharField(choices=[('construction', 'Construction'), ('hospitality', 'Hospitality'), ('legal', 'Legal'), ('tech', 'Technology'), ('youth', 'Youth Protection'), ('other', 'Other')], max_length=50)),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TechTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_model', models.TextField()),
                ('data_flow', models.TextField()),
                ('access_control', models.TextField()),
                ('compliance_refs', models.JSONField(default=list)),
                ('owasp_mitigations', models.JSONField(default=list)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_model', to='portfolio.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='stack',
            field=models.ManyToManyField(to='portfolio.techtag'),
        ),
    ]
